name: AndroidApp

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Swift toolchain 5.0.3 
      run: wget https://swift.org/builds/swift-5.0.3-release/xcode/swift-5.0.3-RELEASE/swift-5.0.3-RELEASE-osx.pkg;
        sudo installer -pkg swift-5.0.3-RELEASE-osx.pkg -target /
    - name: Install NDK
      run: wget https://dl.google.com/android/repository/android-ndk-r17c-darwin-x86_64.zip;
        unzip android-ndk-r17c-darwin-x86_64.zip
    - name: Install Swift Android Toolchain
      run: SWIFT_ANDROID=$(curl --silent "https://api.github.com/repos/readdle/swift-android-toolchain/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/');
        wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android-$SWIFT_ANDROID.zip;
        unzip swift-android-$SWIFT_ANDROID.zip;
        rm -rf swift-android-$SWIFT_ANDROID.zip;
        swift-android-$SWIFT_ANDROID/bin/swift-android tools --update;
        ln -sfn swift-android-$SWIFT_ANDROID swift-android-current
    - name: Build all variants
      run: export TOOLCHAINS=org.swift.50320190830a;
        export SWIFT_ANDROID_ARCH=x86_64;
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r17c;
        export SWIFT_ANDROID_HOME=$(pwd)/swift-android-current;
        export PATH=$ANDROID_NDK_HOME:$PATH;
        export PATH=$SWIFT_ANDROID_HOME/bin:$SWIFT_ANDROID_HOME/build-tools/current:$PATH;
        cd android;
        ./gradlew app:build


    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}/android/app/build/outputs/apk/debug/app-debug.apk
